version: '3'
services:
  mysql:
    container_name: mysql
    hostname: mysql-server
    image: mysql:8.4.2
    environment:
      - MYSQL_DATABASE=crm_app
      - MYSQL_USER=crm_user
      - MYSQL_PASSWORD=4en14Q1w2e3r4t5*
      - MYSQL_ROOT_PASSWORD=4en14Q1w2e3r4t5*
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d:ro
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
  crm_backend:
    container_name: crm_backend
    hostname: crm-backend-server
    image: python:3.11
    entrypoint:
      - ./entrypoint_dev.sh
    depends_on:
      - mysql
    volumes:
      - ./requirements.txt:/root/requirements.txt:ro
      - ./backend_api.py:/root/backend_api.py:ro
      - ./entrypoint_dev.sh:/entrypoint_dev.sh:ro
    ports:
      - 5000:5000
  web_server:
    container_name: web_server
    hostname: web-server
    image: python:3.11
    entrypoint:
      - ./entrypoint_web_dev.sh
    depends_on:
      - mysql
      - crm_backend
    volumes:
      - ./requirements.txt:/root/requirements.txt:ro
      - ./entrypoint_web_dev.sh:/entrypoint_web_dev.sh:ro
      - ./web_server.py:/root/web_server.py:ro
      - ./index.html:/root/templates/index.html:ro
      - ./form.html:/root/templates/form.html:ro
      - ./welcome.html:/root/templates/welcome.html:ro
      - ./formlist.html:/root/templates/formlist.html:ro
      - ./scripts/:/root/templates/scripts/:ro
      - ./styles/:/root/templates/styles/:ro
    ports:
      - 80:80